synthea:
  install_directory: "/Users/zellaking/Repos/synthea"
openai:
  api_key: ${OPENAI_API_KEY}
  batch_size: 20
  delay_on_error: 1
  backoff_on_error: 2
  max_delay_on_error: 360
  retry_attempts: 10
comprehendmedical:
  profile: default
  service: comprehendmedical
cache:
  file_name: "./cache.sqlite"
pcm:
  path_to_julia: "/opt/homebrew/bin/julia"
